name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: dimo414/ci

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        ls /
        which -a bazel
        mkdir publish
        date > publish/index.md
    - name: Publish
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine
    
    steps:
    - uses: actions/checkout@v1
    - name: shellcheck
      run: sh -c "find . -name '*.sh' | xargs shellcheck"
